apiVersion: v1
kind: Service
metadata:
  name: cloudforge
  namespace: cloudforge
spec:
  selector:
    app: cloudforge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer